spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.type.mapping]": event:com.sankha.orderservice.events.OrderPlacedEvent
#        spring:
#          json:
#            type:
#              mapping: event:com.programmingtechie.orderservice.event.OrderPlacedEvent
server:
  port: 9080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  tracing:
    sampling:
      probability: 1.0


#  resilience4j.circuitbreaker.instances.inventory.event-consumer-buffer-size=10
#  resilience4j.circuitbreaker.instances.inventory.slidingWindowType=COUNT_BASED
#  resilience4j.circuitbreaker.instances.inventory.slidingWindowSize=5
#  resilience4j.circuitbreaker.instances.inventory.failureRateThreshold=50
#  resilience4j.circuitbreaker.instances.inventory.waitDurationInOpenState=5s
#  resilience4j.circuitbreaker.instances.inventory.permittedNumberOfCallsInHalfOpenState=3
#  resilience4j.circuitbreaker.instances.inventory.automaticTransitionFromOpenToHalfOpenEnabled=true

#Resilinece4j Properties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      inventory:
        maxAttempts: 3
  timelimiter:
    instances:
      inventory:
        timeoutDuration: 3s


