spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: product-service
  application:
    name: product-service
server:
  port: 0 #8989

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/