spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: product-service
  application:
    name: product-service
server:
  port: 8989

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"