spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: inventory-service
server:
  port: 0 #8787

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411

  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus